# Project: Project CS200
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = Game.o main.o Media.o Movie.o
LINKOBJ  = Game.o main.o Media.o Movie.o
LIBS     = -L"G:/Programming/IDEs/CPP/Dev-Cpp/MinGW64/lib" -L"G:/Programming/IDEs/CPP/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"G:/Programming/IDEs/CPP/Dev-Cpp/MinGW64/include" -I"G:/Programming/IDEs/CPP/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"G:/Programming/IDEs/CPP/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"G:/Programming/IDEs/CPP/Dev-Cpp/MinGW64/include" -I"G:/Programming/IDEs/CPP/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"G:/Programming/IDEs/CPP/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"G:/Programming/IDEs/CPP/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = "Project CS200.exe"
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

Game.o: Game.cpp
	$(CPP) -c Game.cpp -o Game.o $(CXXFLAGS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

Media.o: Media.cpp
	$(CPP) -c Media.cpp -o Media.o $(CXXFLAGS)

Movie.o: Movie.cpp
	$(CPP) -c Movie.cpp -o Movie.o $(CXXFLAGS)
